use BIG12BB;

if (OBJECT_ID('MATCHUP') is not null)
	drop table MATCHUP;

if (OBJECT_ID('NETWORK') is not null)
	drop table NETWORK;

if (OBJECT_ID('PLAYER') is not null)
	drop table PLAYER;

if (OBJECT_ID('TEAM') is not null)
	drop table TEAM;

if (OBJECT_ID('COACH') is not null)
	drop table COACH;

if (OBJECT_ID('LOCATION') is not null)
	drop table LOCATION;

if (OBJECT_ID('ARENA') is not null)
	drop table ARENA;

CREATE TABLE ARENA (
	ARENAID INT IDENTITY(11,1) PRIMARY KEY,
	ARENANAME VARCHAR(40),
	CAPACITY INT)

CREATE TABLE LOCATION (
	LOCATIONID INT IDENTITY(10,1) PRIMARY KEY,
	CITY VARCHAR(30),
	STATES VARCHAR(20),
	ARENAID INT NOT NULL,
	CONSTRAINT FKLOCATIONTOARENA FOREIGN KEY(ARENAID) REFERENCES ARENA(ARENAID))


CREATE TABLE COACH (
	COACHID INT IDENTITY(1,1) PRIMARY KEY,
	COACHNAME VARCHAR(30),
	SALARY INT)

CREATE TABLE TEAM(
	TEAMID INT IDENTITY(20,1) PRIMARY KEY,
	TEAMNAME VARCHAR(50),
	SCHOOL VARCHAR(50),
	LOCATIONID INT NOT NULL,
	COACHID INT NOT NULL,

	CONSTRAINT FKTEAMTOLOCATION FOREIGN KEY(LOCATIONID) REFERENCES LOCATION(LOCATIONID),
	CONSTRAINT FKTEAMTOCOACH FOREIGN KEY(COACHID) REFERENCES COACH(COACHID))

CREATE TABLE PLAYER (
	PLAYERID INT IDENTITY(10,1) PRIMARY KEY,
	PLAYERNAME VARCHAR(30),
	PLAYERYEAR INT,
	TEAMID INT NOT NULL,
	
	CONSTRAINT CHPLAYERYEAR CHECK (PLAYERYEAR <= 5),
	CONSTRAINT FKPLAYERTOTEAM FOREIGN KEY(TEAMID) REFERENCES TEAM(TEAMID))

CREATE TABLE NETWORK(
	NETWORKID INT IDENTITY(1,1) PRIMARY KEY,
	NETWORKNAME VARCHAR(30))

CREATE TABLE MATCHUP(
	MATCHUPID INT IDENTITY(100,1) PRIMARY KEY,
	HOMETEAMID INT NOT NULL,
	AWAYTEAMID INT NOT NULL,
	MATCHUPDATE DATE NULL,
	MATCHUPTIME TIME NULL,
	NETWORKID INT NOT NULL

	CONSTRAINT FKMARCHUPTOHOMETEAM FOREIGN KEY(HOMETEAMID) REFERENCES TEAM(TEAMID),
	CONSTRAINT FKMARCHUPTOAWAYTEAM FOREIGN KEY(AWAYTEAMID) REFERENCES TEAM(TEAMID),
	CONSTRAINT FKMARCHUPTONETWORK FOREIGN KEY(NETWORKID) REFERENCES NETWORK(NETWORKID)
	)




	








	


